# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Prepare Docker-CE repositories for {{ ansible_os_family }}
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "repo-{{ ansible_os_family | lower }}.yml"
    - "repo-default.yml"
  when:
    - ansible_os_family in ['Debian', 'RedHat']

- name: Installing Docker Community Edition
  ansible.builtin.include_role:
    name: jcook3701.utils.pkg_manager
  vars:
    pkg_manager_pkgs: "{{ docker_ce_pkgs + docker_ce_compose_pkgs }}"
    pkg_manager_state: present
    pkg_manager_update_cache: true

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: "{{ docker_ce_service }}"
    state: started
    enabled: true

- name: Configure Docker Community Edition
  ansible.builtin.include_tasks: configure.yml
