# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
lightdm_pkg_names:
  - lightdm
  - lightdm-gtk-greeter

lightdm_file:
  config: "{{ lightdm_directory.config }}/lightdm.conf"
  xsession: .xsession
