# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
chrony_os_user: "chrony"
chrony_os_group: "chrony"

chrony_os_service: "chronyd"

chrony_os_pkg_names:
  - chrony

chrony_os_directory:
  conf: "/etc"
  log: "/var/log/chrony"
  state: "/var/lib/chrony"
