# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
chrony_pkgs:
  - chrony

chrony_directory:
  conf: "/etc/chrony"
  log: "/var/log/chrony"
  var_state: "/var/lib/chrony"

chrony_service: chronyd
