# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Create LDAP configuration directory
  ansible.builtin.file:
    path: "{{ openldap_directory.conf }}"
    state: directory
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: "0750"

- name: Deploy client configuration (ldap.conf)
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: "{{ openldap_directory.conf }}/ldap.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart openldap service

- name: Ensure openldap listens on Port ({{ openldap_port }})
  ansible.builtin.lineinfile:
    path: "{{ openldap_directory.defaults }}"
    regexp: >-
      ^{{ openldap_sysconfig_variable }}=
    line: >-
      {{ openldap_sysconfig_variable }}="{{ openldap_final_daemon_args }}"
  notify: Restart openldap service

- name: Flush handlers to ensure openldap running with new ports
  ansible.builtin.meta: flush_handlers
