# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: "Include variables from {{ site_item.server_vars }}"
  ansible.builtin.include_vars:
    file: "sites/{{ site_item.server_vars }}"

- name: "Create site configuration for {{ nginx_site.server_name }}"
  ansible.builtin.template:
    src: nginx_site.j2
    dest: "/etc/nginx/sites-available/{{ nginx_site.server_name }}.conf"
    mode: "0644"
  notify: Reload NGINX
