# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Install sdkman
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman-install.sh
    mode: "0755"
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"

- name: Run sdkman install script
  ansible.builtin.command:
    cmd: /tmp/sdkman-install.sh
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"
