# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install Kerberos packages
  ansible.builtin.package:
    name: "{{ kerberos_pkg_names }}"
    state: present

- name: Create Kerberos configuration files
  ansible.builtin.include_tasks: file-generation.yml

- name: Configure Kerberos
  ansible.builtin.include_tasks: configure.yml

- name: Generate Kerberos Keys
  ansible.builtin.include_tasks: keys.yml

- name: Ensure Kerberos service is started and enable
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: started
    enabled: true
  loop: "{{ kerberos_services }}"
  loop_control:
    loop_var: service
  when: kerberos_node_type in ['master', 'replica']
