# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure Kerberos service is stopped and disabled
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: false
  loop:
    - "{{ kerberos_kdc_service }}"
    - "{{ kerberos_admin_service }}"
    - "{{ kerberos_kprop_service }}"
  loop_control:
    loop_var: service
  failed_when: false

- name: Uninstall Kerberos packages
  ansible.builtin.package:
    name: "{{ kerberos_server_pkgs + kerberos_replica_pkgs + kerberos_client_pkgs }}"
    state: absent
