# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
my_vagrant_boxes:
  - { server_vars: default-workstation.yml }

my_vagrant_roles:
# Gui Tools
  - jcook3701.pkgs.xfce
  - jcook3701.pkgs.lightdm
# - jcook3701.pkgs.i3
  - jcook3701.pkgs.google_chrome
# - jcook3701.pkgs.virtualbox
# Package Installers
  - jcook3701.pkgs.flatpak
  - jcook3701.pkgs.docker_ce
  - jcook3701.pkgs.snap
# Developer tools
  - jcook3701.pkgs.sdkman
  - jcook3701.pkgs.nvm
  - jcook3701.pkgs.rbenv
  - jcook3701.pkgs.ruby
  - jcook3701.pkgs.rust
  - jcook3701.pkgs.rustup
  - jcook3701.pkgs.ctop
# - jcook3701.pkgs.mutt
# - jcook3701.pkgs.ros2
# Extras
  - jcook3701.pkgs.mixxx
# TODO:
# - jcook3701.pkgs.sssd
