# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
my_vagrant_boxes:
  - { server_vars: windows-10-workstation.yml }

# my_vagrant_roles:
#  - jcook3701.pkgs.openldap
