# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Include Docker User Group Management Tasks
  ansible.builtin.include_tasks: groups.yml
  when: docker_ce_manage_group | default(true) | bool

- name: Deploy Docker Daemon Configuration Engine
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "{{ docker_ce_file.daemon_json | default('/etc/docker/daemon.json') }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify: Restart docker service
  when: docker_ce_manage_config | bool

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: "{{ docker_ce_service | default('docker') }}"
    state: started
    enabled: true
  become: true
