# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Uninstall Github CLI package and dependencies
  ansible.builtin.package:
    name: "{{ gh_pkg_names }}"
    state: absent
