# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Force deep purge of AnyDesk packages
  ansible.builtin.include_role:
    name: jcook3701.utils.pkg_manager
  vars:
    pkg_manager_pkgs: "{{ anydesk_pkg_names | default(['anydesk']) }}"
    pkg_manager_state: absent
    pkg_manager_remove_level: complete
