# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
nginx_site:
  server_name: "mixxx"
  listen: 80
  root: "/var/www/mixxx"
  location_path: "/stream/"
  autoindex: "on"
