# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Gather active target systemd service units
  ansible.builtin.service_facts:
  become: true

- name: Ensure Unifi service is started and enabled
  ansible.builtin.systemd:
    name: "{{ unifi_service | default('unifi') }}"
    state: started
    enabled: true
  become: true
  when: (unifi_service ~ '.service' in ansible_facts.services)
