# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Execute Unifi seeding tasks
  ansible.builtin.include_tasks: "01_seed.yml"

- name: Execute Unifi service seeding tasks
  ansible.builtin.include_tasks: "02_groups.yml"
  when: unifi_manage_group | default(true) | bool

- name: Execute Unifi service seeding tasks
  ansible.builtin.include_tasks: "03_service.yml"
