# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Gather target host package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Load Jellyfin OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Jellyfin Install
  ansible.builtin.include_tasks: install.yml
  when: jellyfin_state | default('present') == 'present'

- name: Jellyfin Uninstall
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - jellyfin_state | default('present') == 'absent'
    - jellyfin_pkg_names[0] in ansible_facts.packages
