# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
tailscale_state: present
tailscale_repo_url: https://tailscale.com/install.sh
tailscale_auth_key: null

tailscale_is_server: false
