# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install dhcpd package and dependencies.
  ansible.builtin.package:
    name: "{{ dhcpd_pkg_names }}"
    state: present

- name: Ensure DHCPD service is started and enabled
  ansible.builtin.systemd:
    name: "{{ dhcpd_service }}"
    state: started
    enabled: true
