# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
rsyslog_os_user: "root"
rsyslog_os_group: "root"

rsyslog_os_service: "rsyslogd"
rsyslog_os_dep_pkg_names: []
rsyslog_os_pkg_names:
  - "rsyslog"

rsyslog_os_directory:
  conf: "/etc"
  conf_d: "/etc/rsyslog.d"
  state: "/var/lib/rsyslog"
  log_root: "/var/log"
