# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install Pulse Audio package and dependencies
  ansible.builtin.package:
    name: "{{ pulseaudio_pkg_names + pulseaudio_dep_pkg_names }}"
    state: present

- name: Configure Pulse Audio
  ansible.builtin.include_tasks: "configure.yml"
