# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install Pulse Audio package and dependencies
  ansible.builtin.package:
    name: "{{ pulseaudio_pkg_names }}"
    state: present

- name: Ensure Pulse Audio service is started and enable
  ansible.builtin.systemd:
    name: "{{ pulseaudio_service }}"
    state: started
    enabled: true
