# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
kerberos_user: "krb5kdc"
kerberos_group: "krb5kdc"
kerberos_ldap_group: "openldap"
kerberos_ldap_service: "slapd"

kerberos_server_pkgs:
  - krb5-kdc
  - krb5-admin-server

kerberos_replica_pkgs:
  - krb5-kdc
  - krb5-kpropd

kerberos_client_pkgs:
  - krb5-user

kerberos_shared_libs:
  - python3-kerberos
  - python3-gssapi
  - python3-passlib
  - python3-cryptography
  - python3-pycryptodome

kerberos_kdc_service: "krb5-kdc"
kerberos_admin_service: "krb5-admin-server"
kerberos_kprop_service: "krb5-kpropd"

kerberos_os_directory:
  conf: "/etc"
  kdc_conf: "/etc/krb5kdc"
  log: "/var/log/krb5"
  state: "/var/lib/krb5kdc"
  systemd: "/etc/systemd/system"
  dict: "/usr/share/dict"
  defaults: "/etc/default"

kerberos_os_stash_name: "stash"
kerberos_os_admin_defaults_name: "krb5-admin-server"

kerberos_os_admin_regexp: '^DAEMON_ARGS='
kerberos_os_admin_line: 'DAEMON_ARGS="-N"'
