# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
virtualbox_pkg_deps:
  - binutils
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel-{{ ansible_kernel }}
  - dkms
  - qt5-qtbase-devel

virtualbox_pkgs:
  - "{{ virtualbox_version.redhat_pkg }}"

virtualbox_directory:
  repo: "/etc/yum.repos.d"

virtualbox_file:
  repo: "{{ virtualbox_directories.repo }}/virtualbox.repo"

virtualbox_repo_url: "{{ virtualbox_download_url }}/virtualbox/rpm/el/virtualbox.repo"
