# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
# ====================================================================
# 1. OPTIONAL FEATURE SCHEMA INGESTION
# ====================================================================
- name: Upload specific custom LDIF schema extension to the guest host
  ansible.builtin.copy:
    src: "schema/{{ current_feature_name }}.ldif"
    dest: "{{ openldap_directory.schema }}/{{ current_feature_name }}.ldif"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: "0644"
  become: true

- name: Load optional feature schema extension online
  ansible.builtin.shell:
    cmd: "{{ command }}"
  args:
    executable: /bin/bash
  vars:
    command: >-
      set -o pipefail && iconv -f UTF-8 -t UTF-8
      -c {{ openldap_directory.schema }}/{{ current_feature_name }}.ldif 2>&1 |
      ldapadd -Y EXTERNAL -H ldapi:///
  register: feature_schema_result
  failed_when:
    - feature_schema_result.rc != 0
    - "'duplicate ' not in feature_schema_result.stderr | lower"
    - "'already exists' not in feature_schema_result.stderr | lower"
  changed_when: "'adding new entry' in feature_schema_result.stdout | lower"
  become: true
