# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure Flatpak group exists
  ansible.builtin.group:
    name: "{{ flatpak_group | default('_flatpak') }}"
    state: present
  become: true

- name: Add users to the Flatpak group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ flatpak_group | default('_flatpak') }}"
    append: true
  loop: "{{ flatpak_users | default([]) }}"
  loop_control:
    loop_var: user
    label: "Adding {{ user.name }} to {{ flatpak_group }} group"
  become: true
  when:
    - user.name is defined
    - user.name | length > 0
