# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
vagrant_top_level_domain: "com"
vagrant_second_level_domain: "jcook3701"
vagrant_domain_name: "{{ vagrant_second_level_domain }}.{{ vagrant_top_level_domain }}"

vagrant_plugins:
  - "vagrant-vbguest"

# A master list of all available sites
vagrant_boxes:
  - { server_vars: default-server.yml }
  - { server_vars: default-workstation.yml }
  - { server_vars: pxeboot-server.yml }
  - { server_vars: plex-server.yml }
  - { server_vars: mixxx-server.yml }
  - { server_vars: openldap-server.yml }

# TODO: Setup shutdown to get virtualbox guest additions working
vagrant_shutdown: "(nohup sh -c 'sleep 2 && shutdown -r now' > /dev/null 2>&1 &)"

vagrant_guest_prep_commands:
  debian: "export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3-minimal python3-pip build-essential dkms linux-headers-amd64"
  ubuntu: "apt-get update && apt-get install -y build-essential dkms linux-headers-generic"
  redhat: "dnf install -y gcc make dkms kernel-devel kernel-headers elfutils-libelf-devel"
  arch: "pacman -Sy --noconfirm base-devel linux-headers"
  suse: "zypper install -y -t pattern devel_kernel devel_basis"

vagrant_enabled_boxes: []
