# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Prepare Latest repositories for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "repo-{{ ansible_os_family | lower }}.yml"
    - "repo-default.yml"
  when:
    - ansible_os_family in ['Debian']
  # TODO: Ensure will work with redhat in the future and remove above when.

- name: Install Vagrant
  ansible.builtin.package:
    name: "{{ vagrant_pkg_names }}"
    state: present
  become: true

- name: Install Vagrant plugins
  ansible.builtin.include_tasks: plugins.yml

- name: Inspect the current Vagrant item being processed
  ansible.builtin.debug:
    msg: "Processing box with variables from: {{ vagrant_enabled_boxes }}"

- name: Provision and Configure VMs
  vars:
    # Filter the list once at the block level for readability
    enabled_vms: >-
      {{ vagrant_boxes | selectattr('server_vars', 'in', vagrant_enabled_boxes | map(attribute='server_vars')) | list }}
  ansible.builtin.include_tasks: process-vm.yml
  loop: "{{ enabled_vms }}"
  loop_control:
    loop_var: vagrant_item
