# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    tasks_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Check if Vagrant is installed
  ansible.builtin.shell: command -v vagrant
  register: vagrant_check
  ignore_errors: true
  changed_when: false

- name: Install Vagrant if not present
  ansible.builtin.include_tasks: install.yml
  when: vagrant_check.rc != 0

- name: Install Vagrant plugins
  ansible.builtin.include_tasks: plugins.yml

- name: Inspect the current Vagrant item being processed
  ansible.builtin.debug:
    msg: "Processing box with variables from: {{ vagrant_enabled_boxes }}"

- name: Provision and Configure VMs
  vars:
    # Filter the list once at the block level for readability
    enabled_vms: >-
      {{ vagrant_boxes | selectattr('server_vars', 'in', vagrant_enabled_boxes | map(attribute='server_vars')) | list }}
  ansible.builtin.include_tasks: process-vm.yml
  loop: "{{ enabled_vms }}"
  loop_control:
    loop_var: vagrant_item
