# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Get list of installed vagrant plugins
  ansible.builtin.command: vagrant plugin list
  register: installed_plugins
  changed_when: false
  become: true
  become_user: "{{ sudo_user }}"
  when:
    - sudo_user != "root"

- name: DEBUG | Diagnostic Output
  ansible.builtin.debug:
    msg:
      - "STDOUT: >>>{{ installed_plugins.stdout }}<<<"
      - "PLUGIN_VAR: >>>{{ plugin }}<<<"
      - "VAR_TYPE: {{ vagrant_plugins | type_debug }}"
      - "SEARCH_TEST: {{ not (installed_plugins.stdout is search(plugin)) }}"
  loop: "{{ vagrant_plugins }}"
  loop_control:
    loop_var: plugin

- name: "Vagrant | Ensure required plugins are installed"
  ansible.builtin.command: "vagrant plugin install {{ plugin }}"
  loop: "{{ vagrant_plugins }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin }}"
  become: true
  become_user: "{{ sudo_user }}"
  when:
    - sudo_user != "root"
    - not (installed_plugins.stdout is search(plugin))
