# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install required system binaries for the selected platform
  ansible.builtin.package:
    name: "{{ autofs_package_names }}"
    state: present

- name: Execute Autofs dynamic file system configuration
  ansible.builtin.include_tasks: configure.yml
  when:
    - not autofs_use_sssd | bool
    - autofs_bootstrap_mounts | length > 0

- name: Enforce Autofs service is started and enabled
  ansible.builtin.systemd:
    name: "{{ autofs_service }}"
    state: started
    enabled: true
