# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install Samba package and dependencies.
  ansible.builtin.package:
    name: >-
      {{ samba_pkg_names | default([])
        + (samba_is_server | bool | ternary([], samba_client_dep_pkg_names))
      }}
    state: present

- name: Enforce core parent configuration space integrity
  ansible.builtin.file:
    path: "{{ samba_directory.conf }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Execute Samba Server configuration
  ansible.builtin.include_tasks: configure/server/main.yml
  when: samba_is_server | bool

- name: Execute Samba Client configuration
  ansible.builtin.include_tasks: configure/client/main.yml
  when: not samba_is_server | bool
