# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Stop Samba service — Uninstall and Purge
  ansible.builtin.include_tasks: uninstall.yml
