# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
flatpak_pkgs:
  - flatpak
  # Note: Arch typically includes Flatpak support in the base gnome-software package
  # or as an optional dependency.
  - gnome-software
