# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Restart chrony
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: restarted
  become: true
