# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure Webmin service is stopped and disabled
  ansible.builtin.systemd:
    name: "{{ webmin_service | default('webmin') }}"
    state: stopped
    enabled: false
  become: true
  failed_when: false

- name: Uninstall Webmin
  ansible.builtin.package:
    name: "{{ webmin_pkg_names | default([]) }}"
    state: "absent"
  become: true
