# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Remove generated template files needed for Bind9 configuration
  block:

    - name: Remove named.conf configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.named_conf }}"
        state: absent

    - name: Remove named.conf.options configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.named_conf_local }}"
        state: absent

    - name: Remove named.conf.local configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.named_conf_options }}"
        state: absent

    - name: Remove named.conf.controls configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.named_conf_controls }}"
        state: absent

    - name: Remove named.conf.log configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.named_conf_log }}"
        state: absent

    - name: Remove forward zone configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.forward_zone }}"
        state: absent

    - name: Remove reverse zone configuration file
      ansible.builtin.file:
        path: "{{ bind9_file.reverse_zone }}"
        state: absent

- name: Ensure removal of files needed for Bind9 configuration
  block:

    - name: Remove secroots-file
      ansible.builtin.file:
        path: "{{ bind9_options.secroots_file }}"
        state: absent

    - name: Remove dump-file
      ansible.builtin.file:
        path: "{{ bind9_options.dump_file }}"
        state: absent

    - name: Remove statistics-file
      ansible.builtin.file:
        path: "{{ bind9_options.statistics_file }}"
        state: absent

    - name: Remove memstatistics-file
      ansible.builtin.file:
        path: "{{ bind9_options.memstatistics_file }}"
        state: absent

    - name: Remove recursing-file
      ansible.builtin.file:
        path: "{{ bind9_options.recursing_file }}"
        state: absent

# TODO: Should remove everything in the keys directories
# TODO: Should remove
