# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure key directory exist for each zone
  ansible.builtin.file:
    path: "{{ bind9_key_directory.tsig }}/{{ hostvars[item].hostname | default(item) }}"
    state: directory
    owner: bind
    group: bind
    mode: "0775"
  loop: "{{ groups['all'] }}"

- name: Generate TSIG key (only if it doesn't exist)
  ansible.builtin.command: >-
    tsig-keygen -a hmac-sha256 {{ hostvars[item].hostname | default(item) }}
  args:
    chdir: "{{ bind9_key_directory.tsig }}/{{ hostvars[item].hostname | default(item) }}"
  register: tsig_keygen_output
  loop: "{{ groups['all'] }}"

- name: Save each TSIG key to file
  ansible.builtin.copy:
    content: "{{ item.stdout }}"
    dest: >-
      {{ bind9_key_directory.tsig }}/{{ hostvars[item.item].hostname | default(item.item) }}/{{ hostvars[item.item].hostname | default(item.item) }}-tsig.key
    owner: bind
    group: bind
    mode: "0640"
  loop: "{{ tsig_keygen_output.results }}"

  # TODO: Need to eventually setup template options for RHEL.
- name: Generate named.conf.keys from saved TSIG keys
  ansible.builtin.template:
    src: debian/named.conf.keys.j2
    dest: "{{ bind9_file.named_conf_keys }}"
    owner: bind
    group: bind
    mode: "0640"
  vars:
    bind9_key_directory: "{{ bind9_key_directory }}"
