# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Create directories needed for Bind9 setup
  block:
    - name: Create bind9 base directories
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        group: "{{ bind9_user }}"
        owner: "{{ bind9_user }}"
        mode: "0775"
      loop: "{{ bind9_os_directory.values() | list }}"
      loop_control:
        loop_var: dir
        label: "{{ dir }}"

      # NOTE: This is otherwise handled in bind9-dnssec-keygen-and-sign.yml
    - name: Ensure key directories exist
      ansible.builtin.file:
        path: "{{ zone.key_directory }}"
        state: directory
        owner: "{{ bind9_user }}"
        group: "{{ bind9_user }}"
        mode: "0775"
      loop: "{{ bind9_zones }}"
      loop_control:
        loop_var: zone
        label: "{{ zone.key_directory }}"
      when: zone.inline_signing | bool
