# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install Bind9 package and dependencies
  ansible.builtin.apt:
    name: "{{ bind9_pkg_names }}"
    state: present

- name: Create Bind9 configuration directories
  ansible.builtin.include_tasks: directory-creation.yml

- name: Bind9 DNSSEC keygen
  ansible.builtin.include_tasks: dnssec-keygen-and-sign.yml
  loop: "{{ bind9_zones }}"
  loop_control:
    loop_var: zone
    label: "{{ zone.name }}"
  when: not zone.inline_signing | bool

- name: Bind9 TSIG keygen
  ansible.builtin.include_tasks: tsig-keygen.yml
  when: bind9_generate_tsig_keys | bool

- name: Create Bind9 configuration files
  ansible.builtin.include_tasks: file-generation.yml

- name: Ensure Bind9 service is started and enable
  ansible.builtin.systemd:
    name: "{{ bind9_service }}"
    state: started
    enabled: true
