# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Restart pulseaudio
  ansible.builtin.service:
    name: "{{ pulseaudio_service }}"
    state: restarted
