# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Securely initialize missing LDAP service records in the KDC database
  ansible.builtin.command: >-
    kadmin.local -q "add_principal -randkey {{ service_principal }}"
  vars:
    service_principal: "ldap/{{ ldap_server_fqdn }}"
  loop: "{{ kerberos_ldap_servers }}"
  loop_control:
    loop_var: ldap_server_fqdn
    label: "Seeding database entry for: ldap/{{ ldap_server_fqdn }}}"
  register: _ldap_db_seeding
  failed_when: >-
    (_ldap_db_seeding.rc != 0) and
    ('already exists' not in _ldap_db_seeding.stderr | lower)
  when: inventory_hostname in kerberos_admin_servers
  become: true

- name: Securely append required LDAP service keys on the Master KDC
  ansible.builtin.command: >-
    kadmin.local -q "ktadd -k {{ staging_keytab }} {{ service_principal }}"
  vars:
    staging_keytab: "/tmp/ansible_client_{{ ldap_server_fqdn }}.keytab"
    service_principal: "ldap/{{ ldap_server_fqdn }}"
  loop: "{{ kerberos_ldap_servers }}"
  loop_control:
    loop_var: ldap_server_fqdn
    label: "Injecting LDAP keys for: {{ ldap_server_fqdn }}"
  when: inventory_hostname in kerberos_admin_servers
  become: true
