# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Execute Enterprise Host OS Principal Pipeline
  ansible.builtin.include_tasks: hosts.yml
  when:
    - kerberos_client_nodes | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise CIFS File Sharing Principal Pipeline
  ansible.builtin.include_tasks: cifs.yml
  when:
    - kerberos_samba_file_servers | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise NFS Secure UNIX Storage Principal Pipeline
  ansible.builtin.include_tasks: nfs.yml
  when:
    - kerberos_nfs_file_servers | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise HTTP Single Sign-On Principal Pipeline
  ansible.builtin.include_tasks: http.yml
  when:
    - kerberos_http_servers | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise LDAP Secure Directory Principal Pipeline
  ansible.builtin.include_tasks: ldap.yml
  when:
    - kerberos_ldap_servers | length > 0
    - kerberos_node_type == 'master'

- name: Check if transit keys are already merged on Master
  ansible.builtin.command: "klist -k {{ kerberos_keytabs.system_default }}"
  register: master_kt_check
  changed_when: false
  failed_when: false
  when:
    - kerberos_node_type == 'master'
    - false

# read_kt {{ kerberos_keytabs.system_default }}
- name: Merge transit keys natively into the master default system keytab
  ansible.builtin.shell:
    cmd: |
      ktutil <<EOF
      read_kt {{ kerberos_keytabs.master_transit_file }}
      write_kt {{ kerberos_keytabs.system_default }}
      quit
      EOF
  args:
    executable: /bin/bash
  register: read_kt_output
  changed_when: >-
    (read_kt_output.rc == 0) and
    ('error' not in read_kt_output.stdout | lower) and
    ('failed' not in read_kt_output.stdout | lower)
  failed_when: >-
    (read_kt_output.rc != 0) or
    ('error' in read_kt_output.stdout | lower) or
    ('failed' in read_kt_output.stdout | lower) or
    ('error' in read_kt_output.stderr | lower) or
    ('failed' in read_kt_output.stderr | lower) or
    ('permission denied' in read_kt_output.stderr | lower)
  when:
    - kerberos_node_type == 'master'
  become: true

- name: Fetch fully compiled multi-service client keytabs back to the Ansible controller
  ansible.builtin.fetch:
    src: "{{ target_client_file }}"
    dest: "{{ target_controller_staging }}"
    flat: true
  vars:
    target_node: "{{ host_node_fqdn.split('.') | first }}"
    target_client_file: "{{ kerberos_keytabs.master_transit_file }}"
    target_controller_staging: "{{ kerberos_keytabs.controller_client_staging }}"
  loop: "{{ kerberos_client_nodes | default([]) }}"
  loop_control:
    loop_var: host_node_fqdn
    label: "Caching completed passport to controller for: {{ host_node_fqdn }}"
  when: kerberos_node_type == 'master'

# Developer Note: deploy.yml should not be called here.
# - name: Execute unconditional global system keytab delivery passes
#  ansible.builtin.include_tasks: deploy.yml
