# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Execute Enterprise Kiprop OS Transit Pipeline
  ansible.builtin.include_tasks: kiprop/transit.yml
  when:
    - kerberos_client_nodes | default([]) | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise Host OS Transit Pipeline
  ansible.builtin.include_tasks: hosts/transit.yml
  when:
    - kerberos_client_nodes | default([]) | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise CIFS File Sharing Transit Pipeline
  ansible.builtin.include_tasks: cifs/transit.yml
  when:
    - kerberos_samba_file_servers | default([]) | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise NFS Secure UNIX Storage Transit Pipeline
  ansible.builtin.include_tasks: nfs/transit.yml
  when:
    - kerberos_nfs_file_servers | default([]) | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise HTTP Single Sign-On Transit Pipeline
  ansible.builtin.include_tasks: http/transit.yml
  when:
    - kerberos_http_servers | default([]) | length > 0
    - kerberos_node_type == 'master'

- name: Execute Enterprise LDAP Secure Directory Transit Pipeline
  ansible.builtin.include_tasks: ldap/transit.yml
  when:
    - kerberos_ldap_servers | default([]) | length > 0
    - kerberos_node_type == 'master'
