# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Uninstall nano package
  ansible.builtin.apt:
    name: "{{ nano_pkgs }}"
    state: absent
