# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Uninstall ripping and encoding tools
  ansible.builtin.package:
    name: "{{ handbrake_pkgs }}"
    state: absent
  become: true
