# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
openldap_sysconfig_variable: SLAPD_SERVICES

openldap_pkg_names:
  - slapd
  - ldap-utils

openldap_shared_libs:
  - libsasl2-modules-gssapi-mit
  - libnet-ldap-perl

openldap_directory:
  conf: "/etc/ldap"
  slapd: "/etc/ldap/slapd.d"
  certs: "/etc/ldap/certs"
  database: "/var/lib/ldap"
  modules: "/usr/lib/ldap"
  schema: "/etc/ldap/schema"
  run: "/run/slapd"
  defaults: "/etc/default/slapd"

openldap_user: "openldap"
openldap_group: openldap
