# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
openldap_user: "openldap"
openldap_group: "openldap"

openldap_service: "slapd"

# Place holders for OS-specific variables
openldap_sysconfig_variable: "SLAPD_SERVICES"

openldap_pkg_names: []
openldap_shared_libs: []

openldap_directory:
  conf: "{{ (openldap_os_directory | default({'conf': '/etc/ldap'})).conf }}"
  slapd: "{{ (openldap_os_directory | default({'slapd': '/etc/ldap/slapd.d'})).slapd }}"
  certs: "{{ (openldap_os_directory | default({'certs': '/etc/ldap/certs'})).certs }}"
  database: "{{ (openldap_os_directory | default({'database': '/var/lib/ldap'})).database }}"
  modules: "{{ (openldap_os_directory | default({'modules': '/usr/lib/ldap'})).modules }}"
  schema: "{{ (openldap_os_directory | default({'schema': '/etc/ldap/schema'})).schema }}"
  run: "{{ (openldap_os_directory | default({'run': '/run/slapd'})).run }}"
  defaults: "{{ (openldap_os_directory | default({'defaults': '/etc/default/slapd'})).defaults }}"
  backup: "{{ openldap_backup_dir }}"

openldap_schemas_base:
  - core
  - cosine
  - inetorgperson
  - nis
  - openldap
  - collective
  - corba
  - duaconf
  - dyngroup
  - java
  - misc
  - namedobject
  - pmi

openldap_schemas: >-
  {{
    openldap_schemas_base +
    ( ['ppolicy'] if (openldap_ppolicy | default(false)) else [] ) +
    ( ['samba'] if (openldap_samba | default(false)) else [] ) +
    ( ['sudo'] if (openldap_sudo | default(false)) else [] ) +
    ( ['autofs'] if (openldap_autofs | default(false)) else [] ) +
    ( ['guacConfigGroup'] if (openldap_guac | default(false)) else [] )
  }}

## Network & Service Access Binding ##
openldap_raw_port: >-
  {% if openldap_use_tls | bool %}
    {{ 636 | to_json }}
  {% else %}
    {{ 389 | to_json }}
  {% endif %}

openldap_port: "{{ openldap_custom_port | default(openldap_raw_port | from_json, true) }}"

openldap_raw_listen_protocols: >-
  {% if openldap_use_tls | bool %}
    {{ ['ldap', 'ldaps'] | to_json }}
  {% else %}
    {{ ['ldap'] | to_json }}
  {% endif %}

openldap_listen_protocols: "{{ openldap_raw_listen_protocols | from_json }}"

openldap_final_daemon_args: >-
  {% set links = [] %}
  {% for proto in openldap_listen_protocols %}
    {% if proto == 'ldap' %}
      {% set _ = links.append('ldap://0.0.0.0:' ~ openldap_port) %}
    {% elif proto == 'ldaps' %}
      {% set _ = links.append('ldaps://0.0.0.0:' ~ openldap_port) %}
    {% endif %}
  {% endfor %}
  {% set _ = links.append('ldapi:///') %}
  {{ links | join(' ') | trim }}
