# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
openldap_sysconfig_variable: "SLAPD_URLS"

openldap_pkg_names:
  - openldap-servers
  - openldap-clients

openldap_directory:
  conf: "/etc/openldap"
  slapd: "/etc/openldap/slapd.d"
  certs: "/etc/openldap/certs"
  database: "/var/lib/ldap"
  modules: "/usr/lib64/openldap"
  schema: "/etc/openldap/schema"
  run: "/run/openldap"
  defaults: "/etc/sysconfig/slapd"

openldap_user: "ldap"
openldap_group: ldap
