# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
lightdm_desktop_envs:
  - xfce
  - gnome
  - kde

lightdm_window_manager: xfce4
lightdm_session_manager: xfce4-session
lightdm_greeter: lightdm-gtk-greeter

lightdm_directory:
  config: "/etc/lightdm/"
