# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Generate Template files needed for SSSD configuration
  notify: Restart sssd
  block:

    - name: Generate sssd.conf configuration file
      ansible.builtin.template:
        src: sssd.conf.j2
        dest: "{{ sssd_file.sssd_conf }}"
        group: root
        owner: root
        mode: "0555"
