# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Load SSSD OS-specific variables
  ansible.builtin.include_vars: "{{ sssd_vars }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"
  loop_control:
    loop_var: sssd_vars
    label: "Loading variables file: {{ sssd_vars }}"

- name: Install SSSD packages
  ansible.builtin.include_tasks: state/install.yml
  when: sssd_state | default('present') == 'present'

- name: Uninstall SSSD packages
  ansible.builtin.include_tasks: state/uninstall.yml
  when: sssd_state | default('present') == 'absent'

- name: Teardown SSSD
  ansible.builtin.include_tasks: state/teardown.yml
  when: sssd_state | default('present') == 'teardown'
