# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Import SSSD variables.
  ansible.builtin.include_tasks:
    file: sssd-import-vars.yml

- name: Install SSSD package and dependencies.
  ansible.builtin.apt:
    name: "{{ sssd_pkg_names }}"
    state: present

- name: Create SSSD configuration files
  ansible.builtin.include_tasks:
    file: sssd-file-generation.yml
