# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure shared storage directories exist
  ansible.builtin.file:
    path: "{{ share.path }}"
    state: directory
    mode: "0775"
  loop: "{{ samba_shares }}"
  loop_control:
    loop_var: share
    label: "Share path exists for {{ share.name }}"

- name: Execute Classic NT4 Domain Engine branch
  ansible.builtin.include_tasks: nt4/main.yml
  when: samba_deployment_mode == "nt4"

- name: Execute Modern Active Directory Domain Engine branch
  ansible.builtin.include_tasks: addc/main.yml
  when: samba_deployment_mode == "addc"
