# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Setup Unifi Package Repository
  ansible.builtin.include_role:
    name: jcook3701.utils.repo_add
  vars:
    repo_add_id: "{{ unifi_repo_id }}"
    repo_add_name: "{{ unifi_repo_name }}"
    repo_add_enabled: true
    # Debian Overrides (Passed cleanly when running on Debian nodes)
    repo_add_debian_uris: "{{ unifi_debian_uris | default(omit) }}"
    repo_add_debian_suites: "{{ unifi_debian_suites | default(omit) }}"
    repo_add_debian_components: "{{ unifi_debian_component | default(omit) }}"
    repo_add_debian_signed_by: "{{ unifi_debian_signed_by | default(omit) }}"
    # Red Hat Overrides
    repo_add_redhat_baseurl: "{{ unifi_redhat_baseurl | default(omit) }}"
    # Arch Linux Overrides
    repo_add_arch_server: "{{ unifi_arch_server | default(omit) }}"
  when: ansible_os_family in ['Debian', 'Redhat']

- name: Installing Unifi
  ansible.builtin.include_role:
    name: jcook3701.utils.pkg_manager
  vars:
    pkg_manager_pkgs: >-
      {{ unifi_dep_pkg_names | default([])
          + unifi_pkg_names | default(['unifi']) }}
    pkg_manager_state: present
    pkg_manager_update_cache: true

- name: Configure Unifi
  ansible.builtin.include_tasks: configure/main.yml
