# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Configure Ubuntu Systemd Storage Sandbox Overrides
  when: kerberos_node_type in ['master', 'replica']
  block:
    - name: Create systemd override directories for active node services
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ service }}.service.d"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop: "{{ ['krb5-kdc'] + ((kerberos_node_type == 'master') | ternary(['krb5-admin-server'], ['krb5-kpropd'])) }}"
      loop_control:
        loop_var: service
        label: "Systemd Service Override Directory -> /etc/systemd/system/{{ service }}.service.d"

    - name: Inject systemd log path write overrides
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ service }}.service.d/override.conf"
        content: |
          [Service]
          ReadWritePaths={{ kerberos_directory.log }}/ {{ kerberos_directory.state }}/
        mode: "0644"
        owner: root
        group: root
      loop: "{{ ['krb5-kdc'] + ((kerberos_node_type == 'master') | ternary(['krb5-admin-server'], ['krb5-kpropd'])) }}"
      loop_control:
        loop_var: service
        label: "Systemd Storage Sandbox Configuration -> /etc/systemd/system/{{ service }}.service.d/override.conf"
      register: _sandbox_overrides_copied

    - name: Force immediate systemd configuration refresh
      ansible.builtin.systemd:
        daemon_reload: true
      when: _sandbox_overrides_copied.changed
