# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Add flathub remote if it does not exist
  ansible.builtin.command: flatpak remote-add --if-not-exists {{ item.name }} {{ item.url }}
  loop: "{{ flatpak_repos }}"
  when: >-
    (item.name is defined and item.name | length > 0) and
    (ansible_facts.packages['flatpak'] is defined)
