# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load Flatpak OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Manage flatpak installation status
  ansible.builtin.package:
    name: "{{ flatpak_pkgs }}"
    state: "{{ flatpak_state }}"

- name: Add flathub remote if it does not exist
  ansible.builtin.command: flatpak remote-add --if-not-exists {{ repo.name }} {{ repo.url }}
  loop: "{{ flatpak_repos }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"
  when:
    - repo.name is defined
    - repo.name | length > 0
    - flatpak_state | default('present') == 'present'
