# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
mdadm_mount_directory: "/media/raid"
mdadm_configuration_directory: "/etc/mdadm"
mdadm_fstab_configuration_directory: "/etc"
