# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
google_chrome_pkg: google-chrome-stable_current_amd64.deb
google_chrome_repo_url: "https://dl.google.com/linux/direct/{{ google_chrome_pkg }}"

google_chrome_file:
  package: "/tmp/{{ google_chrome_pkg }}"
