# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
rbenv_pkg_deps:
  - build-essential
  - git
  - curl
  - zlib1g-dev
  - libssl-dev
  - libreadline-dev
  - libyaml-dev
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - libffi-dev
