# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Rustup Install
  ansible.builtin.include_tasks: install.yml
  when: rustup_state | default('present') == 'present'
