# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_tasks: utilities/sudo_user_facts.yml
  when: sudo_user is not defined

- name: Install rustup
  ansible.builtin.get_url:
    url: "{{ rustup_init_url }}"
    dest: /tmp/rustup-init.sh
    mode: "0755"
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"

- name: Run rustup install script
  ansible.builtin.command:
    cmd: /tmp/rustup-init.sh -y
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"

# TODO: Ensure rustup cargo is correctly path-ed.
#- name: Ensure ~/.cargo/bin is in PATH for bash
#  ansible.builtin.lineinfile:
#    path: "/home/{{ rustup_user }}/.bashrc"
#    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
#    insertafter: EOF
#  become: false
