# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure Replica update server daemon is active
  ansible.builtin.service:
    name: "{{ kerberos_kprop_service }}"
    state: started
    enabled: true
  become: true
  when: kerberos_node_type == 'replica'
