# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Import AppArmor configuration variables
  ansible.builtin.include_vars:
    file: "pkgs-server/apparmor/apparmor-config-vars.yml"
