# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
ansible_pkg_names:
  - python3-devel
  - libffi-devel
  - openssl-devel
  - gcc
  - redhat-rpm-config
  - python3-cffi
  - python3-cffi-backend
