# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    tasks_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Configure global Git settings
  become: true
  become_user: "{{ sudo_user }}"
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "{{ github.username }}" }
    - { name: "user.email", value: "{{ github.email }}" }
