# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Gather active target systemd service units
  ansible.builtin.service_facts:
  become: true

- name: Ensure MongoDB service is stopped and disabled
  ansible.builtin.systemd:
    name: "{{ mongodb_service | default('mongodb') }}"
    state: stopped
    enabled: false
  become: true
  when: (mongodb_service ~ '.service' in ansible_facts.services)

- name: Force deep purge of MongoDB packages
  ansible.builtin.include_role:
    name: jcook3701.utils.pkg_manager
  vars:
    pkg_manager_pkgs: "{{ mongodb_pkg_names | default(['mongodb-org']) }}"
    pkg_manager_state: absent
    pkg_manager_remove_level: complete
