# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
nginx_site:
  server_name: "cockpit"
  listen: 80
  proxy_pass: "https://127.0.0.1:9090"
  is_websocket: true
