# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
nginx_site:
  server_name: "pxeboot"
  listen: 80
  root: "/var/www/html/pxe"
  location_path: "/"
  autoindex: "on"
