# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Generate OpenLDAP password hashes
  ansible.builtin.command: "slappasswd -s {{ password.plain }}"
  loop:
    - { plain: "{{ openldap_admin_password }}", fact: "openldap_admin_password_hashed" }
    - { plain: "{{ openldap_replication_password }}", fact: "openldap_replication_password_hashed" }
  loop_control:
    loop_var: password
    label: "Generating hash for {{ password.fact }}"
  register: openldap_hashed_pass_cmds
  no_log: true
  changed_when: false

- name: Set OpenLDAP hashed passwords as facts
  ansible.builtin.set_fact:
    "{{ hash_result.password.fact }}": "{{ hash_result.stdout }}"
  loop: "{{ openldap_hashed_pass_cmds.results }}"
  loop_control:
    loop_var: hash_result
    label: "Setting fact: {{ hash_result.password.fact }}"
  no_log: true
