# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
# A master list of all sites your role knows how to build
vagrant_boxes:
  - { server_vars: pxeboot-server.yml }
  - { server_vars: plex-server.yml }
  - { server_vars: mixxx-server.yml }

# The selector: This is what you override in your playbook or env vars
# By default, it's empty so nothing happens by accident
vagrant_enabled_boxes: []
