# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Prepare Virtualbox repositories for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "repo-{{ ansible_os_family | lower }}.yml"
    - "repo-default.yml"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Install VirtualBox
  ansible.builtin.package:
    name: "{{ virtualbox_pkg_names }}"
    state: present

- name: Ensure VirtualBox kernel modules are loaded (RedHat)
  ansible.builtin.command: /sbin/vboxconfig
  register: vbox_config_result
  changed_when: "'Stopping' in vbox_config_result.stdout"
  args:
    creates: /lib/modules/{{ ansible_kernel }}/misc/vboxdrv.ko
  when:
    - ansible_os_family == "RedHat"
  failed_when: false

- name: VirtualBox Extension Pack
  ansible.builtin.include_tasks: extension-pack.yml

- name: VirtualBox Configure
  ansible.builtin.include_tasks: configure.yml
