# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Uninstall VirtualBox
  ansible.builtin.package:
    name: "{{ virtualbox_pkg_names }}"
    state: absent

- name: Remove VirtualBox group
  ansible.builtin.group:
    name: "{{ virtualbox_group }}"
    state: absent
