# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load chrony OS-specific variables
  ansible.builtin.include_vars: "{{ chrony_vars }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"
  loop_control:
    loop_var: chrony_vars
    label: "Loading variables file: {{ chrony_vars }}"

- name: Ensure Chrony NTP is installed and configured
  ansible.builtin.include_tasks: state/install.yml
  when: chrony_state | default('present') == 'present'

- name: Ensure Chrony NTP is uninstalled
  ansible.builtin.include_tasks: state/uninstall.yml
  when: chrony_state | default('present') == 'absent'

- name: Ensure teardown of Chrony NTP package and configurations
  ansible.builtin.include_tasks: state/teardown.yml
  when: chrony_state | default('present') == 'teardown'
