# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Installing Flatpak package and dependencies
  ansible.builtin.package:
    name: >-
      {{ flatpak_dep_pkg_names | default([])
          + flatpak_pkg_names | default([]) }}
    state: present
  become: true

- name: Ensure Flatpak is configured
  ansible.builtin.include_tasks: configure/main.yml
