# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load Fail2ban OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Gather target host package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Fail2ban packages
  ansible.builtin.include_tasks: install.yml
  when: fail2ban_state | default('present') == 'present'

- name: Uninstall Fail2ban packages
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - fail2ban_state | default('present') == 'absent'
    - fail2ban_pkg_names[0] in ansible_facts.packages

- name: Teardown Fail2ban
  ansible.builtin.include_tasks: teardown.yml
  when:
    - fail2ban_state | default('present') == 'teardown'
