# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure Master KDC service is running before propagation
  ansible.builtin.service:
    name: "{{ kerberos_kdc_service }}"
    state: started
  when: kerberos_node_type == 'master'

- name: Ensure Master Administration server is running before propagation
  ansible.builtin.service:
    name: "{{ kerberos_admin_service }}"
    state: started
  when: kerberos_node_type == 'master'
