# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Restart gssproxy service
  ansible.builtin.service:
    name: "{{ gssproxy_service }}"
    state: restarted
  become: true
  when:
    - gssproxy_state == 'present'
    - gssproxy_manage_service | bool
