# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load Prometheus OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Gather target host package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Prometheus packages
  ansible.builtin.include_tasks: install.yml
  when: prometheus_state | default('present') == 'present'

- name: Uninstall Prometheus packages
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - prometheus_state | default('present') == 'absent'
    - prometheus_pkg_names[0] in ansible_facts.packages
