# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load LightDM OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install LightDM and Greeter
  ansible.builtin.package:
    name: "{{ lightdm_pkgs }}"
    state: present

- name: Enable and start LightDM service
  ansible.builtin.systemd:
    name: lightdm
    enabled: yes
    state: started

- name: Configure LightDM service
  ansible.builtin.include_tasks: configure.yml
