# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
bind9_pkg_names:
  - bind
  - bind-utils

bind9_rfc1918: "named.rfc1912.zones"

bind9_root_key: "named.root.key"

bind9_configuration_directory: "/etc"
bind9_options_directory: "/var/named"
bind9_dynamic_keys_directory: "/run/named/"
bind9_root_key_directory: "/etc"

bind9_root_zone:
  - zone: "."
    type: "hint"
    file: "named.ca"

# Don't edit below this line
bind9_os_directory:
  conf: "{{ bind9_configuration_directory }}"
  zone: "{{ bind9_configuration_directory }}/zones"
  keys: "{{ bind9_configuration_directory }}/keys"
  root_keys: "{{ bind9_root_key_directory }}"
  options: "{{ bind9_options_directory }}"
  data: "{{ bind9_options_directory }}/data"
  dynamic: "{{ bind9_options_directory }}/dynamic"
  slaves: "{{ bind9_options_directory }}/slaves"
  dynamic_keys: "{{ bind9_options_directory }}/keys"
  run: "{{ bind9_dynamic_keys_directory }}"
