# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Write custom service definition template cleanly to disk
  ansible.builtin.template:
    src: "custom_service.xml.j2"
    dest: "{{ firewalld_directory.services }}/{{ firewalld_in_name }}.xml"
    owner: root
    group: root
    mode: "0644"
  when: firewalld_in_name not in firewalld_native_services
  register: service_template_result

- name: Instantly enable the newly generated service definition
  ansible.posix.firewalld:
    service: "{{ firewalld_in_name }}"
    permanent: true
    state: enabled
    immediate: true
