# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install firewalld package and dependencies.
  ansible.builtin.package:
    name: "{{ firewalld_pkg_names }}"
    state: present
