# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Clean up local controller staging replica keytab cache
  ansible.builtin.file:
    path: "{{ target_controller_transit }}"
    state: absent
  vars:
    target_node: "{{ replica_fqdn.split('.') | first }}"
    target_controller_transit: "{{ kerberos_keytabs.controller_transit_staging }}"
  loop: >-
    {{ kerberos_client_nodes | default([])
        + (kerberos_replica_servers | default([]))
        + [ansible_hostname + '.' + kerberos_domain_name] }}
  loop_control:
    loop_var: replica_fqdn
    label: "Purging controller replica cache -> {{ replica_fqdn }}"
  delegate_to: localhost
  become: false

- name: Clean up local controller staging client keytab cache
  ansible.builtin.file:
    path: "{{ target_controller_client }}"
    state: absent
  vars:
    target_node: "{{ client_fqdn.split('.') | first }}"
    target_controller_client: "{{ kerberos_keytabs.controller_client_staging }}"
  loop: >-
    {{ kerberos_client_nodes | default([])
        + (kerberos_replica_servers | default([]))
        + [ansible_hostname + '.' + kerberos_domain_name] }}
  loop_control:
    loop_var: client_fqdn
    label: "Purging controller client cache -> {{ client_fqdn }}"
  delegate_to: localhost
  become: false

- name: Erase temporary local controllers cached stash file
  ansible.builtin.file:
    path: "/tmp/kerberos_stash_file"
    state: absent
  delegate_to: localhost
  run_once: true
  become: false
