# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
webmin_state: present

webmin_repo_url: https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh
