# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Deploy client-side NFS upcall request-key configuration
  ansible.builtin.template:
    src: "nfs.idmap.conf.j2"
    dest: "{{ nfs_utils_file.nfs_idmap_conf }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  # Only deploy if running in native mode; gssproxy overrides this logic later
  when: not nfs_utils_use_gssproxy | bool
