# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Gather active target systemd service units
  ansible.builtin.service_facts:
  become: true

- name: Ensure native client-side GSS security daemon is active for interception
  ansible.builtin.service:
    name: "{{ nfs_utils_client_service | default('rpc-gssd') }}"
    state: "started"
    enabled: true
  become: true
  when: (nfs_utils_client_service ~ '.service' in ansible_facts.services)

- name: Manage package-provided server-side crypt helper
  ansible.builtin.service:
    name: "{{ nfs_utils_server_helper_service | default('rpc-svcgssd') }}"
    state: "{{ nfs_utils_use_svcgssd | bool | ternary('started', 'stopped') }}"
    enabled: "{{ nfs_utils_use_svcgssd | bool }}"
  become: true
  when: (nfs_utils_server_helper_service ~ '.service' in ansible_facts.services)

- name: Ensure master NFS server daemon is started and enabled
  ansible.builtin.service:
    name: "{{ nfs_utils_server_service | default('nfs-kernel-server') }}"
    state: "started"
    enabled: true
  become: true
  when: (nfs_utils_server_service ~ '.service' in ansible_facts.services)
