# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
ruby_marker: "# {mark} Ansible - System Ruby Setup"
ruby_bashrc: |
  export GEM_HOME="$HOME/.ruby/"
  export PATH="$HOME/.ruby/bin:$PATH"
