# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
# Universal Service Unit and Configuration File Mappings
ssh_service: "ssh"

ssh_pkg_names: []

ssh_directory:
  conf: "{{ ssh_os_directory.conf | default('/etc/ssh') }}"
  pid: "{{ ssh_os_directory.pid | default('/var/run') }}"
  bin: "{{ ssh_os_directory.bin | default('/usr/lib/openssh') }}"

ssh_file:
  conf: "{{ ssh_directory.conf }}/sshd_config"
  pid: "{{ ssh_directory.pid }}/sshd.pid"
  sftp_server: "{{ ssh_directory.bin }}/sftp-server"
