# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install rdiff-backup
  ansible.builtin.package:
    name: "{{ rdiff_backup_pkg_names }}"
    state: present

# TODO: Configure rdiff-backup tasks
