# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Enforce core parent configuration space integrity
  ansible.builtin.file:
    path: "{{ samba_directory.conf }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Bootstrap Samba group and admin user
  ansible.builtin.include_tasks: bootstrap/main.yml
  when: samba_is_server | bool

- name: Execute Samba Server configuration
  ansible.builtin.include_tasks: server.yml
  when: samba_is_server | bool

- name: Execute Samba Client configuration
  ansible.builtin.include_tasks: client.yml
  when:
    - samba_client_mounts | length > 0
