# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
webmin_os_dep_pkg_names:
  - python3-pexpect

webmin_os_pkg_names:
  - webmin
  - libnet-ldap-perl
  - libdbd-pg-perl
  - libdbd-mysql-perl
  - fail2ban
  - certbot
