# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Ensure CIFS Utilities package and dependencies are installed
  ansible.builtin.package:
    name: >-
      {{ cifs_utils_dep_pkg_names | default([])
          + cifs_utils_pkg_names | default([]) }}
    state: present
  become: true

- name: Ensure CIFS Utilities are configured
  ansible.builtin.include_tasks: configure/main.yml
