# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Include necessary variables for vsftpd install
  block:
    - name: Import vsftpd configuration variables
      ansible.builtin.include_vars:
        file: "vsftpd-config-vars.yml"
