# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Import vsftpd variables.
  ansible.builtin.include_tasks:
    file: vsftpd-import-vars.yml

# NOTE: I should probably use ansible.builtin.package or add conditional for other installers.
- name: Install vsftpd package and dependencies.
  ansible.builtin.apt:
    name: "{{ vsftpd_pkg_names }}"
    state: present
