# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install necessary dependencies
  ansible.builtin.apt:
    pkg:
      - python3-pexpect
    state: present

- name: Download Webmin setup script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh
    dest: /tmp/webmin-setup-repos.sh
    mode: "0755"

- name: Run Webmin setup script
  ansible.builtin.expect:
    command: /tmp/webmin-setup-repos.sh
    responses:
      Question:
        - "y"
#    timeout: 600

- name: Run the equivalent of "apt-get update".
  ansible.builtin.apt:
    update_cache: yes

- name: Installing Webmin
  ansible.builtin.apt:
    name: webmin
    state: present
    install_recommends: yes
