# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Installing Webmin
  ansible.builtin.package:
    name: "{{ webmin_pkgs }}"
    state: present

- name: Ensure Webmin service is started and enabled
  ansible.builtin.systemd:
    name: "{{ webmin_service }}"
    state: started
    enabled: yes
