# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
prometheus_state: present

prometheus_exporter: prometheus-node-exporter

prometheus_port: 9100
