# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Include rbenv variables
  ansible.builtin.include_vars: rbenv.yml

- name: Installing necessary packages for rbenv
  ansible.builtin.apt:
    pkg:
      - build-essential
      - git
      - curl
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - libcurl4-openssl-dev
      - libffi-dev
    state: present

- name: Clone rbenv repository
  ansible.builtin.git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ sudo_user_home }}/.rbenv"
    version: master
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"

- name: Clone ruby-build repository
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ sudo_user_home }}/.rbenv/plugins/ruby-build"
    version: master
  become: true
  become_user: "{{ sudo_user }}"
  when: sudo_user != "root"

- name: Update .bashrc for rbenv and ruby-build
  ansible.builtin.blockinfile:
    dest: "{{ sudo_user_home }}/.bashrc"
    marker: "{{ rbenv_marker }}"
    block: "{{ rbenv_bashrc }}"
    state: present
  when: sudo_user != "root" and rbenv_bashrc is defined

- name: Reload Shell
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: reload-shell.yml
