# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install nginx to localhost
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    # Use this variable to chose sites.
    nginx_enabled_sites:
      - { server_vars: pxeboot.yml }
      - { server_vars: mixxx.yml }
  roles:
    - nginx
