# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install nginx to localhost
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    # This is the "Decision" part
    enabled_site_names:
      - pxe.local
      - mixxx.local
  roles:
    - nginx
