# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: "Manage vagrant on localhost"
  hosts: localhost
  gather_facts: true
  become: true
  vars_files:
    - "vars/vagrant/{{ env | default('default-server') }}.yml"
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install vagrant and create virtual machine
      vars:
        vagrant_enabled_boxes: "{{ my_vagrant_boxes }}"
      ansible.builtin.include_role:
        name: jcook3701.pkgs.vagrant

- name: "Configure Vagrant VMs on localhost"
  hosts: vagrant_vms
  gather_facts: true
  become: true
  vars_files:
    - vars/vagrant/main.yml
    - "vars/vagrant/{{ env | default('default-server') }}.yml"
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Apply Common and Profile Roles
      ansible.builtin.include_role:
        name: "{{ current_role }}"
      loop: "{{ common_roles + my_vagrant_roles }}"
      loop_control:
        loop_var: current_role
        label: "{{ current_role }}"
