# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
pulseaudio_dep_pkg_names:
  - alsa-utils

pulseaudio_pkg_names:
  - pulseaudio
  - pulseaudio-utils

pulseaudio_os_directory:
  conf: "/etc/pulse"
  service: "/etc/systemd/system"
  pid: "/var/run/pulse"
