# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
openldap_state: present

openldap_admin_password: "SecretPassword123"

# Domain Options
openldap_top_level_domain: "com"
openldap_second_level_domain: "jcook3701"

openldap_use_ssl: false # TODO: Use this in vars/main.yml

# Extra Schemas
openldap_autofs: false
openldap_guac: false
openldap_ppolicy: false
openldap_samba: false
openldap_sudo: false
