# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
sssd_pkg_names:
  - sssd
  - sssd-tools
  - sssd-ldap
  - sssd-krb5
  - libpam-sss
  - libnss-sss
