# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Load Lutris OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "default.yml"

- name: Prepare Lutris repositories for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
        - "repo-{{ ansible_distribution | lower }}.yml"
        - "repo-{{ ansible_os_family | lower }}.yml"
        - "repo-default.yml"
  # Arch doesn't need repo prep, so we skip it
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Install Lutris
  ansible.builtin.include_tasks: install.yml
  when: lutris_state | default('present') == 'present'

- name: Lutris Uninstall
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - lutris_state | default('present') == 'absent'
    - lutris_pkg_names[0] in ansible_facts.packages
