# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Fix Mixxx Qt6 symbol lookup error (Permanent LD Config)
  become: true
  ansible.builtin.copy:
    dest: /etc/ld.so.conf.d/mixxx-qt6.conf
    content: "/lib/x86_64-linux-gnu/\n"
    mode: "0644"
  notify: Update ldconfig cache

# - name: Add LD_LIBRARY_PATH to bashrc for Mixxx CLI
#  ansible.builtin.lineinfile:
#    path: "{{ ansible_env.HOME }}/.bashrc"
#    # This prepends the path to ensure it's checked FIRST
#    line: 'export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH'
#    state: present
#    create: yes
#    mode: "0644"
