# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Clean up operational local server host certificate signing request files
  ansible.builtin.file:
    path: "{{ openldap_tls_csr }}"
    state: absent
  become: true
  when: openldap_node_type == 'master'

- name: Clean up transient flat certificate staging off the Ansible Controller
  ansible.builtin.file:
    path: "{{ openldap_controller_staging.root_ca_cert }}"
    state: absent
  delegate_to: localhost
  become: false
  run_once: true
  when: openldap_node_type in ['master', 'slave']
