# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Stop and disable tftpd-hpa service
  ansible.builtin.systemd:
    name: "{{ tftpd_hpa_service }}"
    state: stopped
    enabled: false
  failed_when: false

- name: Uninstall tftpd-hpa package and dependencies.
  ansible.builtin.package:
    name: "{{ tftpd_hpa_pkg_names }}"
    state: absent
